site_name: "BANSHEE Documentation"
site_url: "https://docs.banshee.rokubun.cat"
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mononame
    search_index_only: true
repo_url: 'https://github.com/rokubun/banshee-docs'
nav:
  - 'Overview': index.md
  - 'Get started': 'sections/get_started.md'
  - 'Get Your Location':  'sections/get_location.md'
  - 'FAQ': 'faq.md'
  # - 'API Reference': 'faq.md'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search:
  # - pdf-export:
  #     combined: true  
  #     combined_output_path: "pdf/output.pdf"
      

