site_name: "Rokubun's MkDocs template documentation"
site_url: "https://example.rokubun.cat"
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mononame
    search_index_only: true
repo_url: 'http://192.168.1.54:9080/templates/mkdocs.git'
nav:
  - 'Introduction': index.md
  - 'Section 1': 'sections/section.md'
  - 'Section_2': 
    - 'Figures': 'sections/figures.md'
    - 'Tables': 'sections/tables.md'
  - 'FAQs': 'faq.md'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - codehilite


plugins:
  - search:
  # - pdf-export:
  #     combined: true  
  #     combined_output_path: "pdf/output.pdf"
      

